### ISSUE TITLE
does not handle int64

### ISSUE THREAD

**Issue by awclives** [JohnSundell/Wrap#13]
related to this guy: https://github.com/JohnSundell/Unbox/issues/80.

great libraries by the way.

**Comment by awclives** [comment]
adding the following extension from [here](http://stackoverflow.com/questions/27305855/swift-cast-int64-to-anyobject-for-nsmutablearray) seems to fix it:

`extension Int64 : _ObjectiveCBridgeable
{
    public init(_ number: NSNumber)
    {
        self.init(number.longLongValue)
    }
    
    public func _bridgeToObjectiveC() -> NSNumber
    {
        return NSNumber(longLong: self)
    }
    
    public static func _getObjectiveCType() -> Any.Type
    {
        return NSNumber.self
    }
    
    public static func _isBridgedToObjectiveC() -> Bool
    {
        return true
    }
    
    public static func _forceBridgeFromObjectiveC(source: NSNumber, inout result: Int64?)
    {
        result = source.longLongValue
    }
    
    public static func _conditionallyBridgeFromObjectiveC(source: NSNumber, inout result: Int64?) -> Bool
    {
        result = source.longLongValue
        return true
    }
}`

**Comment by JohnSundell** [comment]
Fix included in Wrap 2.0: https://github.com/JohnSundell/Wrap/pull/17

**Comment by JohnSundell** [comment]
Fixed in Wrap 2.0
