### ISSUE TITLE
Migrate to Swift 3

### ISSUE THREAD

**Issue by andreyz** [JohnSundell/Wrap#15]
Gave a try migrating in Xcode 8, got lost in Any/AnyObject hell..

Happy to assist in doing the final migration.

**Comment by awclives** [comment]
does the swift 3 branch not work?  am not able to test myself yet . . .

**Comment by awclives** [comment]
confirmed it does not compile.

**Comment by JohnSundell** [comment]
Yeah, Swift got a pretty substantial update as part of Beta 6 & GM - which includes a major change to how `Any` and `AnyObject` works, which is the reason Wrap won't compile. I'm going to fix this during the upcoming weekend, if no one else beats me to it :)

**Comment by andreyz** [comment]
@JohnSundell I'm happy to assist. Did a stab at it, but still have at least 7 tests always failing, so I ran out of ideas
<img width="255" alt="screen shot 2016-09-15 at 19 48 48" src="https://cloud.githubusercontent.com/assets/205317/18560819/7ed2fd2a-7b7d-11e6-8157-98361e142a99.png">

**Comment by andreyz** [comment]
See PR #16

**Comment by Zeropointer11** [comment]
when would the swift3 branch work?

**Comment by JohnSundell** [comment]
Hey everyone. Sorry for the wait, but I'm pleased to let you know that the `swift3` branch is now fully working again on the relase version of Xcode 8 🎉 Thanks a lot for all your input (especially @andreyz for your reference implementation!) Will soon make `master` use Swift 3 and make a release.

**Comment by awclives** [comment]
Awesome!

**Comment by JohnSundell** [comment]
Also, here's the proposed changes for Wrap 2.0, which will bring Swift 3 to `master`: https://github.com/JohnSundell/Wrap/pull/17 Would love some feedback 😄
