### ISSUE TITLE
Having a class with an NSDate property results in NSJSONSerializer failing

### ISSUE THREAD

**Issue by Codeglee** [JohnSundell/Wrap#2]
`let modelData : NSData = try Wrap(model)`

Fails on this line:

```
func wrap<T>(object: T, writingOptions: NSJSONWritingOptions) throws -> NSData {
     return try NSJSONSerialization.dataWithJSONObject(self.wrap(object, enableCustomizedWrapping: true), options: writingOptions)
}
```

**Comment by JohnSundell** [comment]
Thanks for reporting this @Codeglee! I'll take a look at it asap :)

**Comment by JohnSundell** [comment]
This commit fixes the issue: https://github.com/JohnSundell/Wrap/commit/7f66185e935143d3b4d40c8b7931f9d25279bc1c

**Comment by JohnSundell** [comment]
Will make a new release now :)
