### ISSUE TITLE
Support for CGColor?

### ISSUE THREAD

**Issue by eonist** [JohnSundell/Wrap#20]
Does wrap work with CGColor?

**Comment by JohnSundell** [comment]
@eonist Not out of the box, as serializing code for things like colors, points, sizes, etc tend to be very opinionated and very a lot from app to app. `CGColor` is also a bit tricky type to auto-serialize, as it gets implenented as a private type under the hood in CoreGraphics (at least when bridged to Swift). 

However, it's super easy to add your own Wrap implementation for `UIColor/NSColor` (based on what format you want it to serialize to), and since it's super easy to convert `CGColor` to their Cocoa equivalent, wrapping becomes easy 🎉

Example:

```swift
extension UIColor: WrapCustomizable {
    public func wrap(context: Any?, dateFormatter: DateFormatter?) -> Any? {
        guard let components = self.cgColor.components else {
            return nil
        }
        
        return [
            "red" : components[0],
            "green" : components[1],
            "blue" : components[2],
            "alpha" : components[3]
        ]
    }
}
```

**Comment by eonist** [comment]
Thanks for the swift and thorough reply! I guess there is no magic bullet to Swift reflection after all. I do like how you use extensions to add wrap-features to classes like UIColor. I will try CGTransform tomorrow, wish me luck! My class uses CGColor as its a gradient and gradients use CGColor types. I think this is another question but does wrap support inheritance? I looked though Wrap.swift and couldn't see any evidence of this at first glance. 

```swift
//inheritance can be supported , by traversing down the hierarchy via: mirror.superclassMirror() see: 

var mirror: Mirror? = Mirror(reflecting: child)
repeat {
    for property in mirror!.children {
        print("property: \(property)")
    }
    mirror = mirror?.superclassMirror()
} while mirror != nil
```

From this post: http://stackoverflow.com/a/36721639/5389500

**Comment by JohnSundell** [comment]
Yeah, Wrap does pretty much exactly what the code you posted does [**here**](https://github.com/JohnSundell/Wrap/blob/master/Sources/Wrap.swift#L381), so inheritance is indeed supported ([check this test](https://github.com/JohnSundell/Wrap/blob/master/Tests/WrapTests.swift#L826)). Good luck with implementing customized wrapping for `CGTransform`, shouldn't be a problem :) Let me know if you need any help!

**Comment by eonist** [comment]
I missed that, was looking at the wrap func that takes value, if I may ask: how do you differentiate which wrap func that takes value and object? By inference or?

**Comment by eonist** [comment]
Thought i follow the initial issue up. Found a consistent way to assert if a value is CGColor. "value is CGColor" doesn't work basically. Neither does asserting for" value is WrapCustomizable" etc. CGColor is very troublesome in this regard. Anyways here is a way to assert CGColor type: 

```swift
if CFGetTypeID(someValue) == CGColorGetTypeID() {
    Swift.print("found CGColor")
}
```

**Comment by JohnSundell** [comment]
Nice, really cool!

**Comment by eonist** [comment]
Hey, Ended up with my own Reflection / UnWrapping library. Its not as complete as yours but it renders XML instead of JSON. I mentioned your project as a Thanks note on my blog: http://stylekit.org/blog/2016/10/08/Optimizing-The-Style-manager/ 

Over and out for now. :D
