### ISSUE TITLE
Drop 'NS' extensions for Foundation types to support new Swift syntax

### ISSUE THREAD

**Issue by scottrhoyt** [JohnSundell/Wrap#24]
Since the new syntax for `Foundation` types landed with Swift 3.0, I have found that my `URL`s are not being wrapped correctly. It seems the extension on `NSURL` to conform to `WrapCustomizable` is not being used. I fixed this by manually extending `URL` in a similar fashion. I'd suspect that this would be the case for other `Foundation` types.

**Comment by JohnSundell** [comment]
Fixed in Wrap 2.0.1: https://github.com/JohnSundell/Wrap/releases/tag/2.0.1
