### ISSUE TITLE
macOS 10.9

### ISSUE THREAD

**Issue by maxsz** [JohnSundell/Wrap#25]
I was wondering if you could lower the OS X/macOS deployment target to 10.9. I don't see why Wrap wouldn't work on 10.9?

Thanks, Max

P.S.: Awesome library! :)

**Comment by JohnSundell** [comment]
Sure, why not? 😃 Wanna make a PR?

**Comment by maxsz** [comment]
Done 👍

**Comment by JohnSundell** [comment]
Awesome 🎉
