### ISSUE TITLE
SPM testing (swift test) not working

### ISSUE THREAD

**Issue by rayfix** [JohnSundell/Wrap#28]
PR #27 Fixes `swift build` but doesn't allow for SPM testing.  A better fix is to create a testing module.
```
swift test
Compile Swift Module 'Wrap' (1 sources)
error: no tests found to execute, create a module in your `Tests' directory
````

**Comment by JohnSundell** [comment]
Resolved in https://github.com/JohnSundell/Wrap/commit/16e41b907d6681cde6f6838367affdf7e4d8ef58 🎉
