### ISSUE TITLE
How to transform a single value before wrapping?

### ISSUE THREAD

**Issue by SuperTango** [JohnSundell/Wrap#32]
I have a model that looks something like:
```
@objc enum MessageType: Int {
    case message
    case kick
}

@objc class PLChatMessage: NSObject, Unboxable, WrapCustomizable {
    let message: String
    let type: MessageType
}
```

Note I'm using classes and not structs as well as a Int enum because these need to be used in ObjC code as well as swift.  

The JSON for this object should look like:
```
{
    "message": "blah blah",
    "type": "message"
}
```

In my class, I have the following for Unboxing:
```
    required init(unboxer: Unboxer) throws {
        self.message = try unboxer.unbox(key: "message")
        let typeString: String = try unboxer.unbox(key: "type")
        if (typeString == "message") {
            self.type = ChatMessageType.message
        } else if (typeString == "nudge") {
            self.type = ChatMessageType.nudge
        } else {
            throw UnboxPathError.invalidDictionaryValue(typeString, "type")
        }
    }
```

So far, so good. I can deserialize from JSON fine (although I think there's a better way to do the deserialization of the "type" parameter that I don't know. 

However, if I want to serialize this, i cant find a way to have a "transformer" for only a single member variable.  The only thing I've found so far is 

```    
    func wrap(context: Any?, dateFormatter: DateFormatter?) -> Any? {
        return [
            // the entire dictionary
        ]
    }
```

But that seems really sub-optimal since in reality, my object is pretty big (not just 2 values).

**Comment by carvin** [comment]
Instead of adding WrapCustomizable to your PLChatMessage class, you should add it to the ChatMessage class. Then, you can just return the string:

```
func wrap(context: Any?, dateFormatter: DateFormatter?) -> Any? {
     switch(self){
          case .message: return "message"
          case .nudge: return "nudge"
     }
}
```

If you don't need the `MessageType` enum to be `Int`, you could also make it type `String` and use `UnboxableEnum` and `WrappableEnum` to do this automatically for you.

```
enum MessageType : String, UnboxableEnum, WrappableEnum {
     case .message = "message"
     case .nudge = "nudge"
}
```

**Comment by SuperTango** [comment]
As I said, the enum has to be an Int as I need to use it in our legacy Objective C codebase.

Also, when using `func wrap(context: Any?, dateFormatter: DateFormatter?) -> Any? `, you have to return the ENTIRE object dictionary, and forego all of Wrap's helpers to serialize the data.  Is there a callback per member variable?

**Comment by JohnSundell** [comment]
What @carvin suggests is a great solution! 👍

Also note that his solution doesn't require you to change the raw value of `MessageType` - it can still be `Int`. Another option is to implement the following method from `WrapCustomizable` in `PLChatMessage`:

```
func wrap(propertyNamed propertyName: String, originalValue: Any, context: Any?, dateFormatter: DateFormatter?) throws -> Any?
```

It enables you to override wrapping on a per-property basis, like you were looking for 🙂

**Comment by SuperTango** [comment]
Thanks!
