### ISSUE TITLE
Support for arrays?

### ISSUE THREAD

**Issue by klaas** [JohnSundell/Wrap#4]
Have you thought of supporting wrapping of arrays? Something along the lines of:

````
public func WrapArray<T>(objects: [T], dateFormatter: NSDateFormatter? = nil) throws -> [WrappedDictionary] {
	let mapped = try objects.map { object in
		return try Wrapper(dateFormatter: dateFormatter).wrap(object, enableCustomizedWrapping: true)
	}
	
	return mapped
}
````

JSON top level objects can be arrays:
<http://stackoverflow.com/questions/3833299/can-an-array-be-top-level-json-text>

Kind regards,
Klaas.

PS: I'm really liking your wrap/unbox approach!

**Comment by JohnSundell** [comment]
Hi @klaas, happy to let you know that this is now supported: https://github.com/JohnSundell/Wrap/commit/43527527597f0dd425c9aa55eaf014b93ba1c7f2 :)

**Comment by JohnSundell** [comment]
Thanks for highlighting this issue!

**Comment by clayellis** [comment]
I'm still getting an InvalidTopLevelObject with an array of structs that are all Unboxable. Are there any known limitations to wrapping arrays?

**Comment by clayellis** [comment]
Sorry, I should've been more persistent in solving my own problem before spamming. My bad. For those who get hung up on this and didn't take the time to look at the link John posted:

    let fooArray: [Foo] = ...
    let wrappedFooArray: [WrappedDictionary] = try Wrap(fooArray)

Great work @JohnSundell! I'm a huge fan of Unbox and Wrap.

**Comment by JohnSundell** [comment]
No problems @clayellis, happy that you like Unbox & Wrap 🎉
