### ISSUE TITLE
How to get the resulting JSON string?

### ISSUE THREAD

**Issue by TomasHubelbauer** [JohnSundell/Wrap#42]
Hello, sorry if I missed something totally obvious, but does this library support serializing the resulting dictionary to an actual JSON string?

**Comment by JohnSundell** [comment]
Hey @TomasHubelbauer! No problem, just return `Data` from `wrap()` and create a `String` from it, like this:

```swift
let data = try wrap(object) as Data
let string = String(data: data, encoding: .utf8)
```

**Comment by TomasHubelbauer** [comment]
Ah, okay. Cool! Thank you.
