### ISSUE TITLE
Warning in XCode 9.1: 'characters' is deprecated

### ISSUE THREAD

**Issue by tomasikp** [JohnSundell/Wrap#48]
[Wrap/Sources/Wrap.swift:265:63](https://github.com/JohnSundell/Wrap/blob/master/Sources/Wrap.swift#L265): 'characters' is deprecated: Please use String or Substring directly

**Comment by JohnSundell** [comment]
Fixed in Wrap 3.0.0 that now uses Swift 4 🎉 Thanks for bringing this up @tomasikp 👍

**Comment by tomasikp** [comment]
np @JohnSundell 👍 💯
