### ISSUE TITLE
how to use func wrap(propertyNamed ?

### ISSUE THREAD

**Issue by davidseek** [JohnSundell/Wrap#51]
I'm trying the following with a struct with 20+ values.

```
func wrap(propertyNamed propertyName: String, originalValue: Any, context: Any?, dateFormatter: DateFormatter?) throws -> Any? {
        
        if propertyName == "color" {
            return self.color.toHexString
        }
        
        return originalValue
    }
``` 

Called by 

```
var serialized: WrappedDictionary {
        
        do {
            
            return try Wrap.wrap(self)
            
        } catch let error {
            
            print(error)
            fatalError("Error wrapping ClientInspection: ")
        }
    }
```

This approach crashes with `(lldb)`
What am I missing? Helps is very appreciated.

Basically I just want to transform this one value in this particular case.
David

**Comment by JohnSundell** [comment]
Hi @davidseek 👋 I think the crash is caused by your call to `fatalError`. On the line before you are printing the actual error that occurred while wrapping, what does it say?

**Comment by davidseek** [comment]
Hey. Sorry I did not get back to you. 
I will close this since I can't reproduce it since I went another approach because I got stuck on this issue.
If I come across it again, I'll reopen.
