### ISSUE TITLE
Wrap -> Unbox -> Wrap Symmetry

### ISSUE THREAD

**Issue by SimplGy** [JohnSundell/Wrap#8]
John, I saw in your video you mention using symmetry as a fun way to unit test these things.

I'd like to enforce every model I write be serialized and deserialized symmetrically, but it's easy to miss  properties and mess this up. Wrap uses `WrapCustomizable` and other methods to configure serialization and Unbox uses the `init(unboxer)`. They know nothing about each other so it's easy to come out of sync.

Have you given any thought to enforcing this symmetry, either by using config data structures, or validation, or something else? Maybe there's a thread of discussion you could point me to?

Wondering if you think joining the two libraries up, or writing a layer above them both, or some other strategy would be a good way to approach this.

I'm working on an approach that creates a higher-level Model abstraction that [enforces symmetrical-ity through a dictionary convention](https://gist.github.com/SimplGy/860c71978176dc1c2a67437fdf568ae4#file-wrap-unbox-symmetrical-swift-L84-L103). It's sort-of working but loses the deeper customization features that Wrap offers.

Is this is a good approach, or would it be better to try to join up the two libraries, or something else (like maybe this isn't an interesting feature to you at all)?

**Comment by rob-nash** [comment]
@SimplGy would you mind posting a link to the video you reference please ?

**Comment by SimplGy** [comment]
Sure thing @rob-nash:

https://vimeo.com/165920052

![image](https://cloud.githubusercontent.com/assets/548809/15335240/b901a018-1c2e-11e6-9e7e-134927bd696e.png)

**Comment by SimplGy** [comment]
Another way to think of this is to say that any JSON-backed model object in an application should conform to `RawRepresentable` where `typealias RawValue = [String:AnyObject]:

```swift
/// A type that can be converted to an associated "raw" type, then
/// converted back to produce an instance equivalent to the original.
public protocol RawRepresentable {
    /// Every distinct value of `self` has a corresponding unique
    /// value of `RawValue`, but `RawValue` may have representations
    /// that do not correspond to a value of `Self`.
    associatedtype RawValue

    /// Convert from a value of `RawValue`, yielding `nil` iff
    /// `rawValue` does not correspond to a value of `Self`.
    public init?(rawValue: Self.RawValue)

    /// `Self(rawValue: self.rawValue)!` is equivalent to `self`.
    public var rawValue: Self.RawValue { get }
}
```

I actually implemented it this way and kind of like it. I had to implement `init?(rawValue:)` with `try! Wrap(self)`, but I think for instances of self generated from json, the wrap function cannot fail because of a run time value, only because of a dev time misconfiguration (amirite?).

**Comment by JohnSundell** [comment]
Very interesting @SimplGy! I really like your idea of being able to perform these tests more or less automatically. What I personally do in my tests is just to manually call `Wrap()` on a model and then `Unbox()` the resulting `NSData`, and then assert that the instances are equal; like this:

```
let userA = User(name: "John", age: 28)
let data: NSData = try Wrap(userA)
let userB: User = try Unbox(data)
XCTAssertEquals(userA, userB)
```

I do think this should be a 3rd stand-alone library though (if possible). I really like the idea of "micro-libraries" that each perform a dedicated task well, but don't include lots of functionality that you might not need. I'm actually working on a more high-level abstraction that combines Unbox, Wrap & network adapters (such as Almofire or CloudKit) into a complete model & syncing handling package. But it still requires some work before I even know that it's a good idea 😄

Also interesting approach to use `RawRepresentable` to represent JSON (de)serializable models. Don't think it's something we should require in either Unbox or Wrap, but it's a nice way of implementing the libraries, as you say.

So, there's no generic way of enforcing symmetry yet, but I think it's definetly something that a more higher level library could do. Let me know if you experiment with this further, perhaps we could join our two approaches into a super library later 😄

**Comment by JohnSundell** [comment]
Closing for now, since there are no immediate actions to be taken, and this issue has had almost 2 weeks of inactivity. Feel free to reply and I'll re-open the issue :)
